#!/usr/bin/env python3
"""Export the distilled per-size student MLPs to a libaom C header.

Emits av1/encoder/partition_student_weights.h: one NN_CONFIG per block size
(8/16/32/64), with weights laid out exactly as av1_nn_predict expects
(weights[node * num_inputs + i], ReLU hidden layers, linear output). The Fase D
integration includes this header and calls av1_nn_predict + av1_nn_softmax; no
new inference code is written.
"""

import argparse
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import torch  # noqa: E402
import student as studentmod  # noqa: E402
import features as featmod  # noqa: E402

LICENSE = """/*
 * Copyright (c) 2024, Alliance for Open Media. All rights reserved.
 *
 * This source code is subject to the terms of the BSD 2 Clause License and
 * the Alliance for Open Media Patent License 1.0. If the BSD 2 Clause License
 * was not distributed with this source code in the LICENSE file, you can
 * obtain it at www.aomedia.org/license/software. If the Alliance for Open
 * Media Patent License 1.0 was not distributed with this source code in the
 * PATENTS file, you can obtain it at www.aomedia.org/license/patent.
 */
"""


def fmt_array(name, values):
    body = ", ".join("{:.8e}f".format(float(v)) for v in values)
    return "static const float {}[] = {{ {} }};\n".format(name, body)


def emit_config(dim, cfg):
    """Return (arrays_text, config_text) for one block size."""
    prefix = "av1_partition_student_{}".format(dim)
    arrays = ""
    w_names, b_names = [], []
    n_layers = cfg["num_hidden_layers"] + 1
    for k in range(n_layers):
        wn = "{}_weight_{}".format(prefix, k)
        bn = "{}_bias_{}".format(prefix, k)
        arrays += fmt_array(wn, cfg["weights"][k])
        arrays += fmt_array(bn, cfg["bias"][k])
        w_names.append(wn)
        b_names.append(bn)
    hidden = ", ".join(str(h) for h in cfg["num_hidden_nodes"]) or "0"
    conf = (
        "static const NN_CONFIG {p}_nnconfig = {{\n"
        "  {ni},  // num_inputs\n"
        "  {no},  // num_outputs\n"
        "  {nl},  // num_hidden_layers\n"
        "  {{ {hid} }},  // num_hidden_nodes\n"
        "  {{ {ws} }},\n"
        "  {{ {bs} }},\n"
        "}};\n"
    ).format(p=prefix, ni=cfg["num_inputs"], no=cfg["num_outputs"],
             nl=cfg["num_hidden_layers"], hid=hidden,
             ws=", ".join(w_names), bs=", ".join(b_names))
    return arrays, conf


def main(argv):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--students", default="/workspace/results/models/student/"
                                        "students.pt")
    p.add_argument("--out", default="/workspace/src/aom/av1/encoder/"
                                    "partition_student_weights.h")
    args = p.parse_args(argv)

    bundle = torch.load(args.students, map_location="cpu")
    dims = sorted(bundle["students"].keys())

    arrays_all, configs_all = "", ""
    for dim in dims:
        net = studentmod.make_student(featmod.NUM_FEATURES, bundle["hidden"])
        net.load_state_dict(bundle["students"][dim])
        cfg = studentmod.export_nn_config(net)
        a, c = emit_config(dim, cfg)
        arrays_all += a + "\n"
        configs_all += c + "\n"

    guard = "AOM_AV1_ENCODER_PARTITION_STUDENT_WEIGHTS_H_"
    switch = "".join(
        "    case {}: return &av1_partition_student_{}_nnconfig;\n".format(
            {8: "BLOCK_8X8", 16: "BLOCK_16X16", 32: "BLOCK_32X32",
             64: "BLOCK_64X64"}[dim], dim) for dim in dims)

    header = (
        LICENSE
        + "\n// Generated by src/scripts/partition_model/export_weights.py -- "
          "do not edit.\n"
          "// Distilled AV1 partition student: per-size MLP, features from\n"
          "// src/scripts/partition_model/features.py (NUM_FEATURES={}).\n"
          "// Output softmax = [P(NONE), P(SPLIT), P(REST)].\n".format(
              featmod.NUM_FEATURES)
        + "#ifndef {g}\n#define {g}\n\n".format(g=guard)
        + '#include "av1/encoder/ml.h"\n#include "av1/common/enums.h"\n\n'
        + "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        + "#define AV1_PARTITION_STUDENT_NUM_FEATURES {}\n\n".format(
            featmod.NUM_FEATURES)
        + arrays_all
        + configs_all
        + "static inline const NN_CONFIG *av1_partition_student_nnconfig(\n"
          "    BLOCK_SIZE bsize) {\n"
          "  switch (bsize) {\n"
        + switch
        + "    default: return NULL;\n  }\n}\n\n"
        + "#ifdef __cplusplus\n}  // extern \"C\"\n#endif\n\n"
        + "#endif  // {}\n".format(guard))

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(header)
    print("wrote", args.out, "for block sizes", dims)


if __name__ == "__main__":
    main(sys.argv[1:])
