#!/usr/bin/env python3
"""Exporta o MLP H9d (39 features, 2 saidas: NAO_EXT/EXT) para um header C
no molde do partition_student_h9c_weights.h.

Emite av1/encoder/partition_student_h9d_weights.h: um NN_CONFIG por tamanho de
bloco (16/32/64), pesos no layout que av1_nn_predict espera. Reusa emit_config
(export_weights.py) e export_nn_config (student.py); reconstroi o net com
make_ext_student (2 saidas) do proprio experimento h9d_predictability.py.

A padronizacao ja esta dobrada na 1a camada (train_ext_student), entao o C
alimenta features CRUS -- identico a convencao do H9a/H9c.

Verificacao de round-trip: para um vetor aleatorio de 39 features, compara o
forward do PyTorch com o forward manual no layout C emitido (deteccao de
qualquer erro de export ANTES de gravar no codificador).
"""
import argparse
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import torch  # noqa: E402
import student as studentmod  # noqa: E402
from export_weights import emit_config, LICENSE  # noqa: E402
from h9d_predictability import make_ext_student  # noqa: E402

PREFIX = "av1_partition_student_h9d"


def c_forward(cfg, x):
    """Forward manual no layout C (av1_nn_predict): weights[node*num_inputs+i],
    ReLU nas ocultas, linear na saida. Retorna logits (sem softmax)."""
    a = np.asarray(x, dtype=np.float64)
    n_layers = cfg["num_hidden_layers"] + 1
    sizes = [cfg["num_inputs"]] + list(cfg["num_hidden_nodes"]) + [cfg["num_outputs"]]
    for k in range(n_layers):
        w = np.asarray(cfg["weights"][k], dtype=np.float64)
        b = np.asarray(cfg["bias"][k], dtype=np.float64)
        n_in, n_out = sizes[k], sizes[k + 1]
        w = w.reshape(n_out, n_in)          # weights[node*num_inputs + i]
        out = w @ a + b
        if k < n_layers - 1:
            out = np.maximum(out, 0.0)      # ReLU nas ocultas
        a = out
    return a


def softmax(z):
    z = np.asarray(z, dtype=np.float64)
    z = z - z.max()
    e = np.exp(z)
    return e / e.sum()


def main(argv):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--students",
                   default="/workspace/results/models/h9d_predictability_h9c/"
                           "students.pt")
    p.add_argument("--out", default="/workspace/src/aom/av1/encoder/"
                                    "partition_student_h9d_weights.h")
    args = p.parse_args(argv)

    bundle = torch.load(args.students, map_location="cpu", weights_only=False)
    nfeat = bundle["num_features"]
    hidden = bundle["hidden"]
    dims = sorted(bundle["students"].keys())
    assert nfeat == 39, "esperado 39 features (h9c set), obtido {}".format(nfeat)

    arrays_all, configs_all = "", ""
    max_err = 0.0
    rng = np.random.default_rng(0)
    for dim in dims:
        net = make_ext_student(nfeat, hidden)
        net.load_state_dict(bundle["students"][dim])
        net.eval()
        cfg = studentmod.export_nn_config(net)
        assert cfg["num_inputs"] == 39 and cfg["num_outputs"] == 2, cfg
        a, c = emit_config(dim, cfg, PREFIX)
        arrays_all += a + "\n"
        configs_all += c + "\n"
        # round-trip: PyTorch vs layout C
        for _ in range(64):
            x = rng.standard_normal(nfeat).astype(np.float32)
            with torch.no_grad():
                py = torch.softmax(net(torch.from_numpy(x)), -1).numpy()
            cc = softmax(c_forward(cfg, x))
            max_err = max(max_err, float(np.abs(py - cc).max()))
    print("round-trip max |PyTorch - C-layout| = {:.3e}".format(max_err))
    assert max_err < 1e-5, "round-trip FALHOU (erro {:.3e})".format(max_err)

    guard = "AOM_AV1_ENCODER_PARTITION_STUDENT_H9D_WEIGHTS_H_"
    switch = "".join(
        "    case {}: return &{}_{}_nnconfig;\n".format(
            {16: "BLOCK_16X16", 32: "BLOCK_32X32", 64: "BLOCK_64X64"}[dim],
            PREFIX, dim) for dim in dims)
    header = (
        LICENSE
        + "\n// Generated by src/scripts/partition_model/h9d_export_weights.py"
          " -- do not edit.\n"
          "// H9d selective extended-partition (AB/4-way) pruner: per-size MLP,\n"
          "// features from features.py node_features_h9c (NUM_FEATURES=39,\n"
          "// A+B+C+E, post-NONE RD context). Output softmax = "
          "[P(NAO_EXT), P(EXT)];\n"
          "// prune AB/4-way search at a node when P(EXT) < tau.\n"
        + "#ifndef {g}\n#define {g}\n\n".format(g=guard)
        + '#include "av1/encoder/ml.h"\n#include "av1/common/enums.h"\n\n'
        + "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        + "#define {}_NUM_FEATURES 39\n\n".format(PREFIX.upper())
        + arrays_all
        + configs_all
        + "static inline const NN_CONFIG *{}_nnconfig(\n"
          "    BLOCK_SIZE bsize) {{\n"
          "  switch (bsize) {{\n".format(PREFIX)
        + switch
        + "    default: return NULL;\n  }\n}\n\n"
        + "#ifdef __cplusplus\n}  // extern \"C\"\n#endif\n\n"
        + "#endif  // {}\n".format(guard))

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(header)
    print("wrote", args.out, "for block sizes", dims)


if __name__ == "__main__":
    main(sys.argv[1:])
